CREATE TABLE IF NOT EXISTS schema."medium_table"
(
"namenumber"VARCHAR(128)NOT NULL,
"code"VARCHAR(100)NOT NULL,
"Sceduledate"TIMESTAMP WITH TIME ZONENOT NULL,
"date"TIMESTAMP WITH TIME ZONENOT NULL,
"name"VARCHAR(130)NOT NULL,
"date"TIMESTAMP WITH TIME ZONENOT NULL,
"name"VARCHAR(131)NULL,
"dateday"TIMESTAMP WITH TIME ZONENULL,
"discription"TEXTNULL,
CONSTRAINT"pk_medium_table"PRIMARY KEY("namenumber")
)
WITH(
OIDS=FALSE
)
TABLESPACE pg_default;